#version: "3.9"
services:


#< ----------- API ------------ >

  api:

    container_name: api

    hostname: api

#    restart: always

    build: ./api/.

    ports:
      - "5000:5000"

#< ----------------------- >