version: "3.8"

services:
  app:
    build: .
    container_name: bookstore_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - CONFIG_FILE=config.yml
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  pgdata:
