services:
  application:
     image: golang:1.23.5
     container_name: rest_api_service
     command: bash -c "go get ./... && go run ."
     working_dir: /app
     ports:
       - 8081:8080
     depends_on:
       - db
     volumes:
       - .:/app
  db:
    image: postgres:latest
    restart: unless-stopped
    container_name: bookDatabase
    hostname: bookDatabase
    ports:
      - 5444:5432
    environment:
      POSTGRES_DB: bookDatabase
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
    volumes:
      - ./data/database.sql:/docker-entrypoint-initdb.d/database.sql